---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - typescript
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true
    exclude_paths:
    - "!**.md"
#  tslint:
#    enabled: true
#    config: tslint.json
checks:
  method-complexity:
    config:
      threshold: 10
exclude_paths:
- "dist/"
- "build/"
- "node_modules/"
- "lib/"
- "test/"
- "docs/"
- "script/"
- "Gruntfile.js"
- "LICENSE"
- "CHANGELOG"
- "*.md"
- "*.json"
