language: node_js
matrix:
  include:
    - node_js: "node"
    - node_js: "lts/*"
    - node_js: "9"
    - node_js: "8"
    - node_js: "7"
env:
  global:
    - CC_TEST_REPORTER_ID=4c5c6925e081383192979bf55a1ef67c3677c21c79e43ed64d5316eb4fa7fa20
notifications:
  slack:
    rooms:
      - altenter-project:Pc8sMyCuHNPBCg1TOw0weD9S#tech
before_install:
  - rm npm-shrinkwrap.json
  - npm i diaspora || npm i https://github.com/GerkinDev/diaspora.git
before_script:
  - |
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    chmod +x ./cc-test-reporter
    ./cc-test-reporter before-build
script:
  - |
    npm run test-coverage
after_script:
  - |
    ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
    - "node_modules"